### PR TITLE
[DRAFT] add i2c support for teensy 4.0 and 4.1

### PR DESCRIPTION
**Pull request by kingbedjed**
still a work in progress but I think following the info in 

https://github.com/Richard-Gemmell/teensy4_i2c - (teensy 4 i2c support README)

https://github.com/nox771/i2c_t3 -  (teensy 3 i2c support README)

https://forum.pjrc.com/threads/62104-Teensy-4-and-4-1-pre-processor-defines?p=247546&viewfull=1#post247546 - (how to distiguish if we are on a teensy 4.0 or 4.1 board)

Still need to test this on a board though...

### CODE REVIEW

**Comment by kingbedjed** [comment]
Things arent compling. Might need to split these path more...

**Comment by hmaarrfk** [comment]
i was playing around with both these libraries too.

I found that both these libraries had their own very strange interpretation of what Wire does.

error handling and all is very different....

thanks for taking a stab at it. I'll back off from my attempt to see how far you get and focus on different things.

I'll circle back here to see if you have any questions I can help with.

**Comment by hmaarrfk** [comment]
Hey Jed,

Thanks for this amazing work!

I think I got it to work out in an other pull request. I didn't want to edit your stuff here for fear of breaking things.

However, the main change I made was to remove the calls to:
```
  err = Wire.getReadError();
```

where did that come from? I'm mostly confused as to why the compiler wasn't complaining.....

**Comment by kingbedjed** [comment]
I think is must be from inherited class? I dont see it in the code, but it was suggested by vscode while I was looking for a replacement for ``err = Wire. getError()``

**Comment by hmaarrfk** [comment]
yeah. I don't think it exists at least not in a useful way. are you using copilot? copilot creates a bunch fake functions I found.

**Pull request merged**
